// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML.Data;
using Microsoft.ML.Transforms;
using System;
using System.Linq;

namespace AzureImage.Model
{
    [CustomMappingFactoryAttribute(nameof(LabelMapping))]
    public class LabelMapping : CustomMappingFactory<LabelMappingInput, LabelMappingOutput>
    {
        public static string[] Label { get; set; } = new string[] { "cloudy", "rain", "shine", "Sunrise", };
        // Custom mapping to determine the label with the highest probability
        public static void Mapping(LabelMappingInput input, LabelMappingOutput output)
        {
            var values = input.output1.GetValues().ToArray();
            var maxVal = values.Max();
            var exp = values.Select(v => Math.Exp(v - maxVal));
            var sumExp = exp.Sum();

            exp.Select(v => (float)(v / sumExp)).ToArray();
            output.score = exp.Select(v => (float)(v / sumExp)).ToArray();

            var maxValue = output.score.Max();
            var maxValueIndex = Array.IndexOf(output.score, maxValue);
            output.label = Label[maxValueIndex];
        }
        // Factory method called when loading the model to get the mapping operation
        public override Action<LabelMappingInput, LabelMappingOutput> GetMapping()
        {
            return Mapping;
        }
    }
    public class LabelMappingInput
    {
        [ColumnName("output1")]
        public VBuffer<float> output1;
    }
    public class LabelMappingOutput
    {

        [ColumnName("PredictedLabel")]
        public string label { get; set; }

        [ColumnName("Score")]
        public float[] score { get; set; }
    }
}
